require("dotenv").config();

module.exports = {
  "local": {
    "username": process.env.DB_USER,
    "password": process.env.DB_PASSWORD,
    "database": process.env.DB_DATABASE,
    "port": process.env.DB_PORT,
    "host": process.env.DB_HOST,
    "dialect": "postgres",
    "seederStorage": "sequelize",
    "logging": console.log,
    "define": {
      "underscored": true,
      "timestamps": true,
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      "deletedAt": "deleted_at",
      lowercase: true,
    },
  },
  "test": {
    "username": process.env.DB_USER,
    "password": process.env.DB_PASSWORD,
    "database": "db-test",
    "port": process.env.DB_PORT,
    "host": process.env.DB_HOST,
    "dialect": "postgres",
    "seederStorage": "sequelize",
    "logging": false,
    "define": {
      "underscored": true,
      "timestamps": true,
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      lowercase: true,
      "deletedAt": "deleted_at",
    },
  },
  "development": {
    "username": process.env.DB_USER,
    "password": process.env.DB_PASSWORD,
    "database": process.env.DB_DATABASE,
    "port": process.env.DB_PORT,
    "host": process.env.DB_HOST,
    "dialect": "postgres",
    "seederStorage": "sequelize",
    "logging": false,
    "define": {
      "underscored": true,
      "timestamps": true,
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      lowercase: true,
      "deletedAt": "deleted_at",
    },
  },
  "production": {
    "username": process.env.DB_USER,
    "password": process.env.DB_PASSWORD,
    "database": process.env.DB_DATABASE,
    "host": process.env.DB_HOST,
    "port": process.env.DB_PORT,
    "dialect": "postgres",
    "seederStorage": "sequelize",
    "logging": false,
    "define": {
      "underscored": true,
      "timestamps": true,
      "createdAt": "created_at",
      "updatedAt": "updated_at",
      lowercase: true,
      "deletedAt": "deleted_at",
    },
  },
};
