
services:
  opti-warehouse-models:
    container_name: opti-warehouse-models
    build:
      context: .
      dockerfile: Dockerfile
      target: production  # Ensure you're building the final production stage
    ports:
      - "${APP_FORWARD_PORT:-5000}:${APP_PORT:-5000}"  # This ensures default ports are used if not set in .env
    volumes:
      - .:/app  # Mount the current directory to the container (be careful with production)
    networks:
      - opti_warehouse_network
    restart: on-failure
    tty: true
    stdin_open: true
    expose:
      - "${APP_PORT:-5000}"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_FORWARD_PORT=5000  # Define these vars if not in the .env file
      - APP_PORT=5000

networks:
  opti_warehouse_network:
    name: opti_warehouse_shared_network  # Ensure this network exists or remove `external: true`
    external: true  # If you want Docker Compose to create this network, remove this line
